# Generated by Django 4.2.7 on 2025-04-24 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='disclosure_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='disclosure_added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='disclosure_added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disclosures_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_cid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disclosureform',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disclosureform',
            name='signature_image_cid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
